apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - app-deployment.yaml
  - app-service.yaml
images:
  - name: 190752870288.dkr.ecr.us-east-1.amazonaws.com/book-ms
    newTag: "1.0"